### ISSUE TITLE
Design QA 1.1: Home Page - Desktop View 

### ISSUE THREAD

**Issue by ghost** [YaleDHLab/dh-rees#2]
- [x] REES Mark: Please use the file **DHREES-logo.svg** in assets folder. Increase in size...top of "studies" aligns with the lower edge of blue nav bar; "east" top edge aligns with top of blue nav bar.
- [x] DHLab Mark: can be increased in size so that it's equal to nav bar height and nudged up 10+ px so that the top of DH overlaps top edge of navy bar. (See **Home-markups.png**) Horizontally center to the parallelogram shape.
- [x] Nav menu links: Set as Interstate Regular (normal) at .9em with letter-spacing at .1em w/ the left margin starting where the top left corner of the parallelogram begins. Then vertically align.
- [x] Add Yale University Logo: **YaleU-logo.svg**
- [x] Remove drop shadows on button elements. For other elements, please set transparency to .5
- [x] Button text: Interstate Regular (normal) at .9em with letter-spacing at .1em
- [x] Add category header above feature image headline.
- [x] Headline Project Title: Set in YaleNew Roman, around 2.5 em / #00356B
- [x] Body Text: Change to AcuminPro, 1 em (15 px) / #00356B
- [x] Date banner: Month - Interstate Black 14 px / Day - Interstate Black 21 px / Increase width of event stripe, ~150%.
- [x] Section Headers: Interstate Regular (normal) at .9em with letter-spacing at .1em. Add "What's New" etc.
- [x] Showcase project titles: YaleNew Regular at 1.6 em; margin-top 24px;
- [x] Featured project heading: give headline text and button 24px top-margin padding
- [x] Banner announcement text: YaleNew Italic, 1.5 em at 33% width / #00356B **The content behind it should be larger, w/ the top right corner or parallelogram aligning to the right of the feature image edge.
- [x] Yale DHLab mark: Align left along same edge as the splash image. "U" and "D" shoudl also align with the left text column edge. Increase the mark's size if needed.
- [x] Use icon files in assets folder: **icon-email.svg / icon-fb.svg / icon-git.svg**
- [x] Increase overlap of beige shape over navy. Looks like the overlay portion gets narrower as you go down the page?

**Comment by duhaime** [comment]
Do you have local access to Acumin-Pro @mongmedia? TypeKit has it, but I'd prefer avoiding TypeKit if this is the only font we need from their service...

**Comment by ghost** [comment]
I use AcuminPro via Typekit. I can look into purchasing the web font today if that helps.

Best,
Monica

On Aug 24, 2016, at 9:19 AM, Douglas Duhaime <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you have local access to Acumin-Pro @mongmediahttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mongmedia&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=r8poZYiiorN0dwkcUsGivI0MEVxJU_WqEKZSiwqE1YE&m=ba0KfdGC4gahdMBJV4O461kILgtly0tp_1MYRaJZghI&s=INO6aKHb9ODfBiwOsLpxkSW-0zAdSTVH7TxqvKQiApg&e=? TypeKit has it, but I'd prefer avoiding TypeKit if this is the only font we need from their service...

**Comment by duhaime** [comment]
It's odd that the stripe appears to get more narrow as one moves down the page. I think it's an optical illusion though--I'm exporting the svg from the background you had mocked, and the beige stripe's angle is 45 (the triangle has no rotation). How does the updated version look?

**Comment by duhaime** [comment]
This should be all set!
